name: Déploiement sur OVH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Déployer via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.cluster026.hosting.ovh.net
          username: funnycreps
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./www/
          server-dir: /www/
          exclude: |
            **/.git*
            **/.git*/**
            **/nbproject/**
